### ISSUE TITLE
Validation Failure (2016-03-20 full data)

### ISSUE THREAD

**Issue by hughamacmullaniv** [NorthernLights/gudid-parser#1]
Hi Mark:

With the latest (2016-03-20) or previous (2016-03-01) GUDID full releases (and accompanying Schema files), after modifying the `data_requirements` list in `dataloader.py`, I'm getting:

```
Validating FULLDownload_Part1_Of_6_2016-03-20.xml
Traceback (most recent call last):
  File "generate_db.py", line 9, in <module>
    loader.validate_xml()
  File "/home/wcit/hughmac/Python/aswans/gudid/dataloader.py", line 62, in validate_xml
    gudid_schema.assertValid(data_doc)
  File "src/lxml/lxml.etree.pyx", line 3491, in lxml.etree._Validator.assertValid (src/lxml/lxml.etree.c:182098)
lxml.etree.DocumentInvalid: Element '{http://www.fda.gov/cdrh/gudid}deviceHCTP': The element is not 'nillable'., line 4174469
```

Any thoughts?

Cheers,
-Hugh

**Comment by hughamacmullaniv** [comment]
Ah: adding `nillable="true"` to the elements that were throwing this error seems to have helped. FYI!

**Comment by MDNukem** [comment]
Yes - if I recall correctly, this seemed like more of a problem with the GUDID data not matching up perfectly with the schemas.

**Comment by hughamacmullaniv** [comment]
Indeed. That's one way to learn about XML and lxml validation bits! :)
